apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # spotigraph
  user: c3BvdGlncmFwaA==
  # waikaadouh2phei3fah1ooxae5eiJ5wo
  password: d2Fpa2FhZG91aDJwaGVpM2ZhaDFvb3hhZTVlaUo1d28=
