version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/go.zenithar.org/spotigraph
    environment:
      GO111MODULE: "on"
      GOBIN: /go/src/go.zenithar.org/spotigraph/bin
    steps:
      - checkout

      - restore_cache:
          key: mod-{{ "go.sum" }}

      - run:
          name: install module
          command: go run mage.go go:deps

      - save_cache:
          key: mod-{{ "go.sum" }}
          paths:
            - /go/pkg/mod
          when: always

      - run:
          name: build
          command: go run mage.go build

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
