version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/go.zenithar.org/spotigraph
    environment:
      GO111MODULE: "on"
      GOBIN: /go/src/go.zenithar.org/spotigraph/bin
    steps:
      - checkout

      - run:
          name: install tools
          command: go run mage.go -d tools

      - run:
          name: build
          command: go run mage.go

      - store_artifacts:
          path: bin

      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
