
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema:
  - schema/common.graphql
  - schema/user.graphql
  - schema/squad.graphql
  - schema/tribe.graphql
  - schema/chapter.graphql
  - schema/guild.graphql

exec:
  filename: generated/exec.go

model:
  filename: generated/models.go

models:
  Error:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.Error
  User:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.Domain_User
  UserCreateInput:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.UserCreateReq
  Squad:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.Domain_Squad
  SquadCreateInput:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.SquadCreateReq
  Tribe:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.Domain_Tribe
  TribeCreateInput:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.TribeCreateReq
  Chapter:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.Domain_Chapter
  ChapterCreateInput:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.ChapterCreateReq
  Guild:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.Domain_Guild
  GuildCreateInput:
    model: go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph.GuildCreateReq

resolver:
  filename: resolver.go
  type: rootResolver
